In [2]:
import pandas as pd
from datetime import datetime, timedelta
# https://oranwind.org/python-pandas-ji-chu-jiao-xue/

## Remove & Add Column

In [14]:
a = pd.read_csv("PM25/Annan.csv", index_col=False)
a.head(5)

,PM25,PM10,rh,temp,so2,o3,rain,no,no2,nox,co,wd,ws,month,week,hr,preasure
0,21.0,53.0,80.0,15.0,1.9,26.0,0.0,0.7,11.0,12.0,0.28,344.0,2.7,1,1,0,1019.8
1,15.0,51.0,79.0,15.1,2.3,28.0,0.0,0.7,11.0,11.0,0.29,344.0,3.9,1,1,1,1019.8
2,25.0,65.0,80.0,15.2,1.8,33.0,0.0,0.9,8.8,9.7,0.27,338.0,3.4,1,1,2,1020.0
3,20.0,54.0,80.0,15.2,2.1,32.0,0.0,0.8,9.2,10.0,0.30,345.0,3.4,1,1,3,1019.7
4,22.0,51.0,81.0,15.1,1.5,29.0,0.0,0.7,10.0,11.0,0.27,343.0,3.2,1,1,4,1019.6

In [15]:
b = a.drop(["rh", "temp", "rain", "no", "nox", "wd", "ws", "preasure"], axis=1)
b.head(5)

   PM25  PM10  so2    o3   no2    co  month  week  hr
0  21.0  53.0  1.9  26.0  11.0  0.28      1     1   0
1  15.0  51.0  2.3  28.0  11.0  0.29      1     1   1
2  25.0  65.0  1.8  33.0   8.8  0.27      1     1   2
3  20.0  54.0  2.1  32.0   9.2  0.30      1     1   3
4  22.0  51.0  1.5  29.0  10.0  0.27      1     1   4

In [17]:
b["測站"] = "安南"
b["空品區"] = "雲嘉南"
b.head(5)

   PM25  PM10  so2    o3   no2    co  month  week  hr  測站  空品區
0  21.0  53.0  1.9  26.0  11.0  0.28      1     1   0  安南  雲嘉南
1  15.0  51.0  2.3  28.0  11.0  0.29      1     1   1  安南  雲嘉南
2  25.0  65.0  1.8  33.0   8.8  0.27      1     1   2  安南  雲嘉南
3  20.0  54.0  2.1  32.0   9.2  0.30      1     1   3  安南  雲嘉南
4  22.0  51.0  1.5  29.0  10.0  0.27      1     1   4  安南  雲嘉南

In [18]:
b.to_csv("Annan.csv", index=False)

## Convert Time

In [17]:
t = datetime(2019, 1, 1)
str(t)

'2019-01-01 00:00:00'

In [18]:
times = []

In [19]:
for i in range(2880):
    times.append(str(t)[:-9])
    t = t + timedelta(days=1)

In [20]:
times

['2019-01-01',
 '2019-01-02',
 '2019-01-03',
 '2019-01-04',
 '2019-01-05',
 '2019-01-06',
 '2019-01-07',
 '2019-01-08',
 '2019-01-09',
 '2019-01-10',
 '2019-01-11',
 '2019-01-12',
 '2019-01-13',
 '2019-01-14',
 '2019-01-15',
 '2019-01-16',
 '2019-01-17',
 '2019-01-18',
 '2019-01-19',
 '2019-01-20',
 '2019-01-21',
 '2019-01-22',
 '2019-01-23',
 '2019-01-24',
 '2019-01-25',
 '2019-01-26',
 '2019-01-27',
 '2019-01-28',
 '2019-01-29',
 '2019-01-30',
 '2019-01-31',
 '2019-02-01',
 '2019-02-02',
 '2019-02-03',
 '2019-02-04',
 '2019-02-05',
 '2019-02-06',
 '2019-02-07',
 '2019-02-08',
 '2019-02-09',
 '2019-02-10',
 '2019-02-11',
 '2019-02-12',
 '2019-02-13',
 '2019-02-14',
 '2019-02-15',
 '2019-02-16',
 '2019-02-17',
 '2019-02-18',
 '2019-02-19',
 '2019-02-20',
 '2019-02-21',
 '2019-02-22',
 '2019-02-23',
 '2019-02-24',
 '2019-02-25',
 '2019-02-26',
 '2019-02-27',
 '2019-02-28',
 '2019-03-01',
 '2019-03-02',
 '2019-03-03',
 '2019-03-04',
 '2019-03-05',
 '2019-03-06',
 '2019-03-07',
 '2019-03-08',
 '2019-03-09',
 '2019-03-10',
 '2019-03-11',
 '2019-03-12',
 '2019-03-13',
 '2019-03-14',
 '2019-03-15',
 '2019-03-16',
 '2019-03-17',
 '2019-03-18',
 '2019-03-19',
 '2019-03-20',
 '2019-03-21',
 '2019-03-22',
 '2019-03-23',
 '2019-03-24',
 '2019-03-25',
 '2019-03-26',
 '2019-03-27',
 '2019-03-28',
 '2019-03-29',
 '2019-03-30',
 '2019-03-31',
 '2019-04-01',
 '2019-04-02',
 '2019-04-03',
 '2019-04-04',
 '2019-04-05',
 '2019-04-06',
 '2019-04-07',
 '2019-04-08',
 '2019-04-09',
 '2019-04-10',
 '2019-04-11',
 '2019-04-12',
 '2019-04-13',
 '2019-04-14',
 '2019-04-15',
 '2019-04-16',
 '2019-04-17',
 '2019-04-18',
 '2019-04-19',
 '2019-04-20',
 '2019-04-21',
 '2019-04-22',
 '2019-04-23',
 '2019-04-24',
 '2019-04-25',
 '2019-04-26',
 '2019-04-27',
 '2019-04-28',
 '2019-04-29',
 '2019-04-30',
 '2019-05-01',
 '2019-05-02',
 '2019-05-03',
 '2019-05-04',
 '2019-05-05',
 '2019-05-06',
 '2019-05-07',
 '2019-05-08',
 '2019-05-09',
 '2019-05-10',
 '2019-05-11',
 '2019-05-12',
 '2019-05-13',
 '2019-05-14',
 '2019-05-15',
 '2019-05-16',
 '2019-05-17',
 '2019-05-18',
 '2019-05-19',
 '2019-05-20',
 '2019-05-21',
 '2019-05-22',
 '2019-05-23',
 '2019-05-24',
 '2019-05-25',
 '2019-05-26',
 '2019-05-27',
 '2019-05-28',
 '2019-05-29',
 '2019-05-30',
 '2019-05-31',
 '2019-06-01',
 '2019-06-02',
 '2019-06-03',
 '2019-06-04',
 '2019-06-05',
 '2019-06-06',
 '2019-06-07',
 '2019-06-08',
 '2019-06-09',
 '2019-06-10',
 '2019-06-11',
 '2019-06-12',
 '2019-06-13',
 '2019-06-14',
 '2019-06-15',
 '2019-06-16',
 '2019-06-17',
 '2019-06-18',
 '2019-06-19',
 '2019-06-20',
 '2019-06-21',
 '2019-06-22',
 '2019-06-23',
 '2019-06-24',
 '2019-06-25',
 '2019-06-26',
 '2019-06-27',
 '2019-06-28',
 '2019-06-29',
 '2019-06-30',
 '2019-07-01',
 '2019-07-02',
 '2019-07-03',
 '2019-07-04',
 '2019-07-05',
 '2019-07-06',
 '2019-07-07',
 '2019-07-08',
 '2019-07-09',
 '2019-07-10',
 '2019-07-11',
 '2019-07-12',
 '2019-07-13',
 '2019-07-14',
 '2019-07-15',
 '2019-07-16',
 '2019-07-17',
 '2019-07-18',
 '2019-07-19',
 '2019-07-20',
 '2019-07-21',
 '2019-07-22',
 '2019-07-23',
 '2019-07-24',
 '2019-07-25',
 '2019-07-26',
 '2019-07-27',
 '2019-07-28',
 '2019-07-29',
 '2019-07-30',
 '2019-07-31',
 '2019-08-01',
 '2019-08-02',
 '2019-08-03',
 '2019-08-04',
 '2019-08-05',
 '2019-08-06',
 '2019-08-07',
 '2019-08-08',
 '2019-08-09',
 '2019-08-10',
 '2019-08-11',
 '2019-08-12',
 '2019-08-13',
 '2019-08-14',
 '2019-08-15',
 '2019-08-16',
 '2019-08-17',
 '2019-08-18',
 '2019-08-19',
 '2019-08-20',
 '2019-08-21',
 '2019-08-22',
 '2019-08-23',
 '2019-08-24',
 '2019-08-25',
 '2019-08-26',
 '2019-08-27',
 '2019-08-28',
 '2019-08-29',
 '2019-08-30',
 '2019-08-31',
 '2019-09-01',
 '2019-09-02',
 '2019-09-03',
 '2019-09-04',
 '2019-09-05',
 '2019-09-06',
 '2019-09-07',
 '2019-09-08',
 '2019-09-09',
 '2019-09-10',
 '2019-09-11',
 '2019-09-12',
 '2019-09-13',
 '2019-09-14',
 '2019-09-15',
 '2019-09-16',
 '2019-09-17',
 '2019-09-18',
 '2019-09-19',
 '2019-09-20',
 '2019-09-21',
 '2019-09-22',
 '2019-09-23',
 '2019-09-24',
 '2019-09-25',
 '2019-09-26',
 '2019-09-27',
 '2019-09-28',
 '2019-09-29',
 '2019-09-30',
 '2019-10-01',
 '2019-10-02',
 '2019-10-03',
 '2019-10-04',
 '2019-10-05',
 '2019-10-06',
 '2019-10-07',
 '2019-10-08',
 '2019-10-09',
 '2019-10-10',
 '2019-10-11',
 '2019-10-12',
 '2019-10-13',
 '2019-10-14',
 '2019-10-15',
 '2019-10-16',
 '2019-10-17',
 '2019-10-18',
 '2019-10-19',
 '2019-10-20',
 '2019-10-21',
 '2019-10-22',
 '2019-10-23',
 '2019-10-24',
 '2019-10-25',
 '2019-10-26',
 '2019-10-27',
 '2019-10-28',
 '2019-10-29',
 '2019-10-30',
 '2019-10-31',
 '2019-11-01',
 '2019-11-02',
 '2019-11-03',
 '2019-11-04',
 '2019-11-05',
 '2019-11-06',
 '2019-11-07',
 '2019-11-08',
 '2019-11-09',
 '2019-11-10',
 '2019-11-11',
 '2019-11-12',
 '2019-11-13',
 '2019-11-14',
 '2019-11-15',
 '2019-11-16',
 '2019-11-17',
 '2019-11-18',
 '2019-11-19',
 '2019-11-20',
 '2019-11-21',
 '2019-11-22',
 '2019-11-23',
 '2019-11-24',
 '2019-11-25',
 '2019-11-26',
 '2019-11-27',
 '2019-11-28',
 '2019-11-29',
 '2019-11-30',
 '2019-12-01',
 '2019-12-02',
 '2019-12-03',
 '2019-12-04',
 '2019-12-05',
 '2019-12-06',
 '2019-12-07',
 '2019-12-08',
 '2019-12-09',
 '2019-12-10',
 '2019-12-11',
 '2019-12-12',
 '2019-12-13',
 '2019-12-14',
 '2019-12-15',
 '2019-12-16',
 '2019-12-17',
 '2019-12-18',
 '2019-12-19',
 '2019-12-20',
 '2019-12-21',
 '2019-12-22',
 '2019-12-23',
 '2019-12-24',
 '2019-12-25',
 '2019-12-26',
 '2019-12-27',
 '2019-12-28',
 '2019-12-29',
 '2019-12-30',
 '2019-12-31',
 '2020-01-01',
 '2020-01-02',
 '2020-01-03',
 '2020-01-04',
 '2020-01-05',
 '2020-01-06',
 '2020-01-07',
 '2020-01-08',
 '2020-01-09',
 '2020-01-10',
 '2020-01-11',
 '2020-01-12',
 '2020-01-13',
 '2020-01-14',
 '2020-01-15',
 '2020-01-16',
 '2020-01-17',
 '2020-01-18',
 '2020-01-19',
 '2020-01-20',
 '2020-01-21',
 '2020-01-22',
 '2020-01-23',
 '2020-01-24',
 '2020-01-25',
 '2020-01-26',
 '2020-01-27',
 '2020-01-28',
 '2020-01-29',
 '2020-01-30',
 '2020-01-31',
 '2020-02-01',
 '2020-02-02',
 '2020-02-03',
 '2020-02-04',
 '2020-02-05',
 '2020-02-06',
 '2020-02-07',
 '2020-02-08',
 '2020-02-09',
 '2020-02-10',
 '2020-02-11',
 '2020-02-12',
 '2020-02-13',
 '2020-02-14',
 '2020-02-15',
 '2020-02-16',
 '2020-02-17',
 '2020-02-18',
 '2020-02-19',
 '2020-02-20',
 '2020-02-21',
 '2020-02-22',
 '2020-02-23',
 '2020-02-24',
 '2020-02-25',
 '2020-02-26',
 '2020-02-27',
 '2020-02-28',
 '2020-02-29',
 '2020-03-01',
 '2020-03-02',
 '2020-03-03',
 '2020-03-04',
 '2020-03-05',
 '2020-03-06',
 '2020-03-07',
 '2020-03-08',
 '2020-03-09',
 '2020-03-10',
 '2020-03-11',
 '2020-03-12',
 '2020-03-13',
 '2020-03-14',
 '2020-03-15',
 '2020-03-16',
 '2020-03-17',
 '2020-03-18',
 '2020-03-19',
 '2020-03-20',
 '2020-03-21',
 '2020-03-22',
 '2020-03-23',
 '2020-03-24',
 '2020-03-25',
 '2020-03-26',
 '2020-03-27',
 '2020-03-28',
 '2020-03-29',
 '2020-03-30',
 '2020-03-31',
 '2020-04-01',
 '2020-04-02',
 '2020-04-03',
 '2020-04-04',
 '2020-04-05',
 '2020-04-06',
 '2020-04-07',
 '2020-04-08',
 '2020-04-09',
 '2020-04-10',
 '2020-04-11',
 '2020-04-12',
 '2020-04-13',
 '2020-04-14',
 '2020-04-15',
 '2020-04-16',
 '2020-04-17',
 '2020-04-18',
 '2020-04-19',
 '2020-04-20',
 '2020-04-21',
 '2020-04-22',
 '2020-04-23',
 '2020-04-24',
 '2020-04-25',
 '2020-04-26',
 '2020-04-27',
 '2020-04-28',
 '2020-04-29',
 '2020-04-30',
 '2020-05-01',
 '2020-05-02',
 '2020-05-03',
 '2020-05-04',
 '2020-05-05',
 '2020-05-06',
 '2020-05-07',
 '2020-05-08',
 '2020-05-09',
 '2020-05-10',
 '2020-05-11',
 '2020-05-12',
 '2020-05-13',
 '2020-05-14',
 '2020-05-15',
 '2020-05-16',
 '2020-05-17',
 '2020-05-18',
 '2020-05-19',
 '2020-05-20',
 '2020-05-21',
 '2020-05-22',
 '2020-05-23',
 '2020-05-24',
 '2020-05-25',
 '2020-05-26',
 '2020-05-27',
 '2020-05-28',
 '2020-05-29',
 '2020-05-30',
 '2020-05-31',
 '2020-06-01',
 '2020-06-02',
 '2020-06-03',
 '2020-06-04',
 '2020-06-05',
 '2020-06-06',
 '2020-06-07',
 '2020-06-08',
 '2020-06-09',
 '2020-06-10',
 '2020-06-11',
 '2020-06-12',
 '2020-06-13',
 '2020-06-14',
 '2020-06-15',
 '2020-06-16',
 '2020-06-17',
 '2020-06-18',
 '2020-06-19',
 '2020-06-20',
 '2020-06-21',
 '2020-06-22',
 '2020-06-23',
 '2020-06-24',
 '2020-06-25',
 '2020-06-26',
 '2020-06-27',
 '2020-06-28',
 '2020-06-29',
 '2020-06-30',
 '2020-07-01',
 '2020-07-02',
 '2020-07-03',
 '2020-07-04',
 '2020-07-05',
 '2020-07-06',
 '2020-07-07',
 '2020-07-08',
 '2020-07-09',
 '2020-07-10',
 '2020-07-11',
 '2020-07-12',
 '2020-07-13',
 '2020-07-14',
 '2020-07-15',
 '2020-07-16',
 '2020-07-17',
 '2020-07-18',
 '2020-07-19',
 '2020-07-20',
 '2020-07-21',
 '2020-07-22',
 '2020-07-23',
 '2020-07-24',
 '2020-07-25',
 '2020-07-26',
 '2020-07-27',
 '2020-07-28',
 '2020-07-29',
 '2020-07-30',
 '2020-07-31',
 '2020-08-01',
 '2020-08-02',
 '2020-08-03',
 '2020-08-04',
 '2020-08-05',
 '2020-08-06',
 '2020-08-07',
 '2020-08-08',
 '2020-08-09',
 '2020-08-10',
 '2020-08-11',
 '2020-08-12',
 '2020-08-13',
 '2020-08-14',
 '2020-08-15',
 '2020-08-16',
 '2020-08-17',
 '2020-08-18',
 '2020-08-19',
 '2020-08-20',
 '2020-08-21',
 '2020-08-22',
 '2020-08-23',
 '2020-08-24',
 '2020-08-25',
 '2020-08-26',
 '2020-08-27',
 '2020-08-28',
 '2020-08-29',
 '2020-08-30',
 '2020-08-31',
 '2020-09-01',
 '2020-09-02',
 '2020-09-03',
 '2020-09-04',
 '2020-09-05',
 '2020-09-06',
 '2020-09-07',
 '2020-09-08',
 '2020-09-09',
 '2020-09-10',
 '2020-09-11',
 '2020-09-12',
 '2020-09-13',
 '2020-09-14',
 '2020-09-15',
 '2020-09-16',
 '2020-09-17',
 '2020-09-18',
 '2020-09-19',
 '2020-09-20',
 '2020-09-21',
 '2020-09-22',
 '2020-09-23',
 '2020-09-24',
 '2020-09-25',
 '2020-09-26',
 '2020-09-27',
 '2020-09-28',
 '2020-09-29',
 '2020-09-30',
 '2020-10-01',
 '2020-10-02',
 '2020-10-03',
 '2020-10-04',
 '2020-10-05',
 '2020-10-06',
 '2020-10-07',
 '2020-10-08',
 '2020-10-09',
 '2020-10-10',
 '2020-10-11',
 '2020-10-12',
 '2020-10-13',
 '2020-10-14',
 '2020-10-15',
 '2020-10-16',
 '2020-10-17',
 '2020-10-18',
 '2020-10-19',
 '2020-10-20',
 '2020-10-21',
 '2020-10-22',
 '2020-10-23',
 '2020-10-24',
 '2020-10-25',
 '2020-10-26',
 '2020-10-27',
 '2020-10-28',
 '2020-10-29',
 '2020-10-30',
 '2020-10-31',
 '2020-11-01',
 '2020-11-02',
 '2020-11-03',
 '2020-11-04',
 '2020-11-05',
 '2020-11-06',
 '2020-11-07',
 '2020-11-08',
 '2020-11-09',
 '2020-11-10',
 '2020-11-11',
 '2020-11-12',
 '2020-11-13',
 '2020-11-14',
 '2020-11-15',
 '2020-11-16',
 '2020-11-17',
 '2020-11-18',
 '2020-11-19',
 '2020-11-20',
 '2020-11-21',
 '2020-11-22',
 '2020-11-23',
 '2020-11-24',
 '2020-11-25',
 '2020-11-26',
 '2020-11-27',
 '2020-11-28',
 '2020-11-29',
 '2020-11-30',
 '2020-12-01',
 '2020-12-02',
 '2020-12-03',
 '2020-12-04',
 '2020-12-05',
 '2020-12-06',
 '2020-12-07',
 '2020-12-08',
 '2020-12-09',
 '2020-12-10',
 '2020-12-11',
 '2020-12-12',
 '2020-12-13',
 '2020-12-14',
 '2020-12-15',
 '2020-12-16',
 '2020-12-17',
 '2020-12-18',
 '2020-12-19',
 '2020-12-20',
 '2020-12-21',
 '2020-12-22',
 '2020-12-23',
 '2020-12-24',
 '2020-12-25',
 '2020-12-26',
 '2020-12-27',
 '2020-12-28',
 '2020-12-29',
 '2020-12-30',
 '2020-12-31',
 '2021-01-01',
 '2021-01-02',
 '2021-01-03',
 '2021-01-04',
 '2021-01-05',
 '2021-01-06',
 '2021-01-07',
 '2021-01-08',
 '2021-01-09',
 '2021-01-10',
 '2021-01-11',
 '2021-01-12',
 '2021-01-13',
 '2021-01-14',
 '2021-01-15',
 '2021-01-16',
 '2021-01-17',
 '2021-01-18',
 '2021-01-19',
 '2021-01-20',
 '2021-01-21',
 '2021-01-22',
 '2021-01-23',
 '2021-01-24',
 '2021-01-25',
 '2021-01-26',
 '2021-01-27',
 '2021-01-28',
 '2021-01-29',
 '2021-01-30',
 '2021-01-31',
 '2021-02-01',
 '2021-02-02',
 '2021-02-03',
 '2021-02-04',
 '2021-02-05',
 '2021-02-06',
 '2021-02-07',
 '2021-02-08',
 '2021-02-09',
 '2021-02-10',
 '2021-02-11',
 '2021-02-12',
 '2021-02-13',
 '2021-02-14',
 '2021-02-15',
 '2021-02-16',
 '2021-02-17',
 '2021-02-18',
 '2021-02-19',
 '2021-02-20',
 '2021-02-21',
 '2021-02-22',
 '2021-02-23',
 '2021-02-24',
 '2021-02-25',
 '2021-02-26',
 '2021-02-27',
 '2021-02-28',
 '2021-03-01',
 '2021-03-02',
 '2021-03-03',
 '2021-03-04',
 '2021-03-05',
 '2021-03-06',
 '2021-03-07',
 '2021-03-08',
 '2021-03-09',
 '2021-03-10',
 '2021-03-11',
 '2021-03-12',
 '2021-03-13',
 '2021-03-14',
 '2021-03-15',
 '2021-03-16',
 '2021-03-17',
 '2021-03-18',
 '2021-03-19',
 '2021-03-20',
 '2021-03-21',
 '2021-03-22',
 '2021-03-23',
 '2021-03-24',
 '2021-03-25',
 '2021-03-26',
 '2021-03-27',
 '2021-03-28',
 '2021-03-29',
 '2021-03-30',
 '2021-03-31',
 '2021-04-01',
 '2021-04-02',
 '2021-04-03',
 '2021-04-04',
 '2021-04-05',
 '2021-04-06',
 '2021-04-07',
 '2021-04-08',
 '2021-04-09',
 '2021-04-10',
 '2021-04-11',
 '2021-04-12',
 '2021-04-13',
 '2021-04-14',
 '2021-04-15',
 '2021-04-16',
 '2021-04-17',
 '2021-04-18',
 '2021-04-19',
 '2021-04-20',
 '2021-04-21',
 '2021-04-22',
 '2021-04-23',
 '2021-04-24',
 '2021-04-25',
 '2021-04-26',
 '2021-04-27',
 '2021-04-28',
 '2021-04-29',
 '2021-04-30',
 '2021-05-01',
 '2021-05-02',
 '2021-05-03',
 '2021-05-04',
 '2021-05-05',
 '2021-05-06',
 '2021-05-07',
 '2021-05-08',
 '2021-05-09',
 '2021-05-10',
 '2021-05-11',
 '2021-05-12',
 '2021-05-13',
 '2021-05-14',
 '2021-05-15',
 '2021-05-16',
 '2021-05-17',
 '2021-05-18',
 '2021-05-19',
 '2021-05-20',
 '2021-05-21',
 '2021-05-22',
 '2021-05-23',
 '2021-05-24',
 '2021-05-25',
 '2021-05-26',
 '2021-05-27',
 '2021-05-28',
 '2021-05-29',
 '2021-05-30',
 '2021-05-31',
 '2021-06-01',
 '2021-06-02',
 '2021-06-03',
 '2021-06-04',
 '2021-06-05',
 '2021-06-06',
 '2021-06-07',
 '2021-06-08',
 '2021-06-09',
 '2021-06-10',
 '2021-06-11',
 '2021-06-12',
 '2021-06-13',
 '2021-06-14',
 '2021-06-15',
 '2021-06-16',
 '2021-06-17',
 '2021-06-18',
 '2021-06-19',
 '2021-06-20',
 '2021-06-21',
 '2021-06-22',
 '2021-06-23',
 '2021-06-24',
 '2021-06-25',
 '2021-06-26',
 '2021-06-27',
 '2021-06-28',
 '2021-06-29',
 '2021-06-30',
 '2021-07-01',
 '2021-07-02',
 '2021-07-03',
 '2021-07-04',
 '2021-07-05',
 '2021-07-06',
 '2021-07-07',
 '2021-07-08',
 '2021-07-09',
 '2021-07-10',
 '2021-07-11',
 '2021-07-12',
 '2021-07-13',
 '2021-07-14',
 '2021-07-15',
 '2021-07-16',
 '2021-07-17',
 '2021-07-18',
 '2021-07-19',
 '2021-07-20',
 '2021-07-21',
 '2021-07-22',
 '2021-07-23',
 '2021-07-24',
 '2021-07-25',
 '2021-07-26',
 '2021-07-27',
 '2021-07-28',
 '2021-07-29',
 '2021-07-30',
 '2021-07-31',
 '2021-08-01',
 '2021-08-02',
 '2021-08-03',
 '2021-08-04',
 '2021-08-05',
 '2021-08-06',
 '2021-08-07',
 '2021-08-08',
 '2021-08-09',
 '2021-08-10',
 '2021-08-11',
 '2021-08-12',
 '2021-08-13',
 '2021-08-14',
 '2021-08-15',
 '2021-08-16',
 '2021-08-17',
 '2021-08-18',
 '2021-08-19',
 '2021-08-20',
 '2021-08-21',
 '2021-08-22',
 '2021-08-23',
 '2021-08-24',
 '2021-08-25',
 '2021-08-26',
 '2021-08-27',
 '2021-08-28',
 '2021-08-29',
 '2021-08-30',
 '2021-08-31',
 '2021-09-01',
 '2021-09-02',
 '2021-09-03',
 '2021-09-04',
 '2021-09-05',
 '2021-09-06',
 '2021-09-07',
 '2021-09-08',
 '2021-09-09',
 '2021-09-10',
 '2021-09-11',
 '2021-09-12',
 '2021-09-13',
 '2021-09-14',
 '2021-09-15',
 '2021-09-16',
 '2021-09-17',
 '2021-09-18',
 '2021-09-19',
 '2021-09-20',
 '2021-09-21',
 '2021-09-22',
 '2021-09-23',
 '2021-09-24',
 '2021-09-25',
 '2021-09-26',
 ...]

In [45]:
a = pd.read_csv("csv/Annan.csv")
a.head(5)

   PM25  PM10  so2    o3   no2    co  month  week  hr  測站  空品區
0  21.0  53.0  1.9  26.0  11.0  0.28      1     1   0  安南  雲嘉南
1  15.0  51.0  2.3  28.0  11.0  0.29      1     1   1  安南  雲嘉南
2  25.0  65.0  1.8  33.0   8.8  0.27      1     1   2  安南  雲嘉南
3  20.0  54.0  2.1  32.0   9.2  0.30      1     1   3  安南  雲嘉南
4  22.0  51.0  1.5  29.0  10.0  0.27      1     1   4  安南  雲嘉南

In [46]:
a.insert(11, "datetime", times)
a.head(5)

,PM25,PM10,so2,o3,no2,co,month,week,hr,測站,空品區,datetime
0,21.0,53.0,1.9,26.0,11.0,0.28,1,1,0,安南,雲嘉南,2019-01-01 00:00:00
1,15.0,51.0,2.3,28.0,11.0,0.29,1,1,1,安南,雲嘉南,2019-01-01 01:00:00
2,25.0,65.0,1.8,33.0,8.8,0.27,1,1,2,安南,雲嘉南,2019-01-01 02:00:00
3,20.0,54.0,2.1,32.0,9.2,0.30,1,1,3,安南,雲嘉南,2019-01-01 03:00:00
4,22.0,51.0,1.5,29.0,10.0,0.27,1,1,4,安南,雲嘉南,2019-01-01 04:00:00

In [47]:
a.to_csv("Annan.csv", index=False)

In [51]:
def csv_modify(file, loc, zone):
    a = pd.read_csv(f"csv/{file}.csv")
    b = a.drop(["rh", "temp", "rain", "no", "nox", "wd", "ws", "preasure"], axis=1)
    b["測站"] = loc
    b["空品區"] = zone
    b.to_csv(f"{file}.csv", index=False)

In [68]:
def csv_modify2(file, loc, zone, header=False):
    a = pd.read_csv(f"csv/{file}.csv")
    b = a.drop(["month", "week", "hr"], axis=1)
    
    t = datetime(2019, 1, 1)
    times = []
    for i in range(2880):
        times.append(str(t))
        t = t + timedelta(hours=1)
        
    b.insert(8, "datetime", times)    
    b.to_csv(f"csv2/{file}.csv", index=False, header=False)

In [69]:
mapping = [["Annan", "安南", "雲嘉南"], 
           ["Banqiao", "板橋", "北部"], 
           ["Cailiao", "菜寮", "北部"], 
           ["Changhua", "彰化", "中部"], 
           ["Chaozhou", "潮州", "高屏"], 
           ["Chiayi", "嘉義", "雲嘉南"], 
           ["Dali", "大里", "中部"], 
           ["Daliao", "大寮", "高屏"], 
           ["Datong", "大同", "北部"], 
           ["Dayuan", "大園", "北部"], 
           ["Dongshan", "冬山", "宜蘭"], 
           ["Douliu", "斗六", "雲嘉南"], 
           ["Erlin", "二林", "中部"], 
           ["Fengshan", "鳳山", "高屏"], 
           ["Fengyuan", "豐原", "中部"], 
           ["FugueiCape", "富貴角", "北部"], 
           ["Fuxing", "復興", "高屏"], 
           ["Guanshan", "關山", "花東"], 
           ["Guanyin", "觀音", "北部"], 
           ["Guanyin", "古亭", "北部"], 
           ["Hengchun", "恆春", "高屏"], 
           ["Hsinchu", "新竹", "竹苗"], 
           ["Hualien", "花蓮", "花東"], 
           ["Hukou", "湖口", "竹苗"], 
           ["Keelung", "基隆", "北部"], 
           ["Kinmen", "金門", "外島"], 
           ["Linkou", "林口", "北部"], 
           ["Linyuan", "林園", "高屏"], 
           ["Longtan", "龍潭", "北部"],
           ["Lunbei", "崙背", "雲嘉南"], 
           ["Magong", "馬公", "外島"], 
           ["Mailiao", "麥寮", "雲嘉南"],
           ["Matsu", "馬祖", "外島"], 
           ["Meinong", "美濃", "高屏"], 
           ["Miaoli", "苗栗", "竹苗"], 
           ["Nantou", "南投", "中部"], 
           ["Nanzi", "楠梓", "高屏"], 
           ["Pingtung", "屏東", "高屏"], 
           ["Pingzhen", "平鎮", "北部"], 
           ["Puli", "埔里", "中部"], 
           ["Puzi", "朴子", "雲嘉南"], 
           ["Qianjin", "前金", "高屏"], 
           ["Qianzhen", "前鎮", "高屏"], 
           ["Qiaotou", "橋頭", "高屏"], 
           ["Renwu", "仁武", "高屏"], 
           ["Sanchong", "三重", "北部"], 
           ["Sanyi", "三義", "竹苗"], 
           ["Shalu", "沙鹿", "中部"], 
           ["Shanhua", "善化", "雲嘉南"], 
           ["Shilin", "士林", "北部"], 
           ["Songshan", "松山", "北部"], 
           ["Tainan", "臺南", "雲嘉南"], 
           ["Taitung", "臺東", "花東"], 
           ["Taixi", "臺西", "雲嘉南"], 
           ["Tamsui", "淡水", "北部"], 
           ["Taoyuan", "桃園", "北部"], 
           ["Toufen", "頭份", "竹苗"], 
           ["Tucheng", "土城", "北部"], 
           ["Wanhua", "萬華", "北部"], 
           ["Wanli", "萬里", "北部"], 
           ["Xianxi", "線西", "中部"], 
           ["Xiaogang", "小港", "高屏"], 
           ["Xindian", "新店", "北部"], 
           ["Xingang", "新店", "雲嘉南"], 
           ["Xinying", "新營", "雲嘉南"], 
           ["Xinzhuang", "新莊", "北部"], 
           ["Xitun", "西屯", "中部"], 
           ["Xizhi", "汐止", "北部"], 
           ["Yangming", "陽明", "北部"], 
           ["Yilan", "宜蘭", "宜蘭"], 
           ["Yonghe", "永和", "北部"], 
           ["Zhongli", "中壢", "北部"], 
           ["Zhongming", "忠明", "中部"], 
           ["Zhongshan", "中山", "北部"], 
           ["Zhudong", "竹東", "竹苗"], 
           ["Zhushan", "竹山", "中部"], 
           ["Zuoying", "左營", "高屏"]]

In [71]:
for idx, m in enumerate(mapping):
    csv_modify2(m[0], m[1], m[2])